taxonomies = {
    'Asset-Type': {
        'url': 'https://www.us-api.morningstar.com/sal/sal-service/{type}/process/asset/v2/',
        'component': 'sal-components-mip-asset-allocation',
        'jsonpath': '$.allocationMap',
        'category': '',
        'percent': 'netAllocation',
        'table': 0,
        'column': 2,
        'map': {
            "AssetAllocNonUSEquity": "Stocks",
            "CANAssetAllocCanEquity": "Stocks",
            "CANAssetAllocUSEquity": "Stocks",
            "CANAssetAllocInternationalEquity": "Stocks",
            "AssetAllocUSEquity": "Stocks",
            "AssetAllocCash": "Cash",
            "CANAssetAllocCash": "Stocks",
            "AssetAllocBond": "Bonds",
            "CANAssetAllocFixedIncome": "Bonds",
            "UK bond": "Bonds",
            "AssetAllocNotClassified": "Other",
            "AssetAllocOther": "Other",
            "CANAssetAllocOther": "Other"
        }
    },
    'Stock-style': {
        'url': 'https://www.us-api.morningstar.com/sal/sal-service/{type}/process/weighting/',
        'component': 'sal-components-mip-style-weight',
        'jsonpath': '$',
        'category': '',
        'percent': '',
        'table': 9,
        'column': 2,
        'map': {"largeBlend": "Large Blend",
                "largeGrowth": "Large Growth",
                "largeValue": "Large Value",
                "middleBlend": "Mid-Cap Blend",
                "middleGrowth": "Mid-Cap Growth",
                "middleValue": "Mid-Cap Value",
                "smallBlend": "Small Blend",
                "smallGrowth": "Small Growth",
                "smallValue": "Small Value",
                }
    },

    'Sector': {
        'url': 'https://www.emea-api.morningstar.com/sal/sal-service/{type}/portfolio/v2/sector/',
        'component': 'sal-components-mip-sector-exposure',
        'jsonpath': '$.EQUITY.fundPortfolio',
        'category': '',
        'percent': '',
        'table': 1,
        'column': 0,
        'map': {"basicMaterials": "Basic Materials",
                "communicationServices": "Communication Services",
                "consumerCyclical": "Consumer Cyclical",
                "consumerDefensive": "Consumer Defensive",
                "energy": "Energy",
                "financialServices": "Financial Services",
                "healthcare": "Healthcare",
                "industrials": "Industrials",
                "realEstate": "Real Estate",
                "technology": "Technology",
                "utilities": "Utilities",
                }
    },
    'Holding': {
        'url': 'https://www.emea-api.morningstar.com/sal/sal-service/{type}/portfolio/holding/v2/',
        'component': 'sal-components-mip-holdings',
        'jsonpath': '$.equityHoldingPage.holdingList[*]',
        'category': 'securityName',
        'percent': 'weighting',
        'table': 6,
        'column': 4,
    },
    'Region': {
        'url': 'https://www.emea-api.morningstar.com/sal/sal-service/{type}/portfolio/regionalSector/',
        'component': 'sal-components-mip-region-exposure',
        'jsonpath': '$.fundPortfolio',
        'category': '',
        'percent': '',
        'table': 2,
        'column': 0,
        'map': {
            "northAmerica": "North America",
            "europeDeveloped": "Europe Developed",
            "asiaDeveloped": "Asia Developed",
            "asiaEmerging": "Asia Emerging",
            "australasia": "Australasia",
            "europeEmerging": "Europe Emerging / Russia",
            "japan": "Japan",
            "latinAmerica": "Central & Latin America",
            "unitedKingdom": "United Kingdom",
            "africaMiddleEast": "Middle East / Africa",
        },
        'map2': {
            "United States": "North America",
            "Canada": "North America",
            "Western Europe - Euro": "Europe Developed",
            "Western Europe - Non Euro": "Europe Developed",
            "Emerging 4 Tigers": "Asia Developed",
            "Emerging Asia - Ex 4 Tigers": "Asia Emerging",
            "Australasia": "Australasia",
            "Emerging Europe": "Europe Emerging / Russia",
            "Japan": "Japan",
            "Central & Latin America": "Central & Latin America",
            "United Kingdom": "United Kingdom",
            "Middle East / Africa": "Middle East / Africa",
            "Not Classified": "Not Classified",
        }
    },
    'Country': {
        'url': 'https://www.emea-api.morningstar.com/sal/sal-service/{type}/portfolio/regionalSectorIncludeCountries/',
        'component': 'sal-components-mip-country-exposure',
        'jsonpath': '$.fundPortfolio.countries[*]',
        'category': 'name', 'percent': 'percent',
        'table': 2,
        'column': 0,
        'map2': {"United States": "UnitedStates", "Canada": "Canada",
                 "Western Europe - Euro": "Western Europe - Euro",
                 "Western Europe - Non Euro": "Western Europe - Non Euro",
                 "Emerging 4 Tigers": "Hong Kong, Singapore, SouthKorea and Taiwan",
                 "Emerging Asia - Ex 4 Tigers": "Asia Emerging",
                 "Australasia": "Australasia",
                 "Emerging Europe": "Europe Emerging / Russia",
                 "Japan": "Japan",
                 "Central & Latin America": "Central & Latin America",
                 "United Kingdom": "United Kingdom",
                 "Middle East / Africa": "Middle East / Africa",
                 "Not Classified": "Not Classified",
                 }
    },
}
